{"trial_id": "04", "hyperparameters": {"space": [{"class_name": "Int", "config": {"name": "n_hidden", "default": 2, "conditions": [], "min_value": 0, "max_value": 8, "step": 1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "n_neurons", "default": null, "conditions": [], "min_value": 16, "max_value": 256, "step": 1, "sampling": "linear"}}, {"class_name": "Float", "config": {"name": "learning_rate", "default": 0.0001, "conditions": [], "min_value": 0.0001, "max_value": 1.0, "step": null, "sampling": "log"}}, {"class_name": "Choice", "config": {"name": "optimiser", "default": "SGD", "conditions": [], "values": ["SGD", "Adam"], "ordered": false}}], "values": {"n_hidden": 5, "n_neurons": 70, "learning_rate": 0.0017030485110152737, "optimiser": "SGD"}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"C:\\ProgramData\\anaconda3\\envs\\hands-on-ml\\lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 273, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"C:\\ProgramData\\anaconda3\\envs\\hands-on-ml\\lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 238, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"C:\\ProgramData\\anaconda3\\envs\\hands-on-ml\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"C:\\ProgramData\\anaconda3\\envs\\hands-on-ml\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n  File \"C:\\ProgramData\\anaconda3\\envs\\hands-on-ml\\lib\\site-packages\\keras_tuner\\src\\engine\\hypermodel.py\", line 149, in fit\n    return model.fit(*args, **kwargs)\n  File \"C:\\ProgramData\\anaconda3\\envs\\hands-on-ml\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"C:\\ProgramData\\anaconda3\\envs\\hands-on-ml\\lib\\site-packages\\tensorflow\\python\\lib\\io\\file_io.py\", line 329, in delete_file_v2\n    _pywrap_file_io.DeleteFile(compat.path_to_bytes(path))\ntensorflow.python.framework.errors_impl.PermissionDeniedError: Failed to delete a file: ./outputs/ch10_ex10_tuned_model\\best_model\\fingerprint.pb.tmpc994f402736e4f72bc2424023f2846c6; Permission denied\n"}